name: commercepal_admin_flutter
description: Commercepal admin flutter app
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # commercepal_admin_flutter: 1.0.0+7
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # di
  injectable: ^2.1.0
  get_it: ^7.2.0

  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0

  # network
  dio: ^5.1.1

  # databases
  floor: ^1.4.1
  sqflite: ^2.2.4+1
  flutter_secure_storage: ^8.0.0

  path_provider:
  flutter_screenutil: ^5.7.0
  cached_network_image: ^3.2.3
  intl:
  image_picker: ^0.8.7+5
  phone_number: ^1.0.0
  email_validator: ^2.1.17
  fimber: ^0.7.0
  shared_preferences: ^2.2.2
  custom_radio_grouped_button: ^2.2.1
  gallery_saver: ^2.3.2
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  font_awesome_flutter: ^10.6.0
  geocoding: ^2.1.1
  url_launcher: ^6.2.2
  qr_code_scanner: ^1.0.1
  otp_text_field: ^1.1.3
  connectivity: ^3.0.6
  onesignal_flutter: ^3.5.1
  upgrader: ^9.0.0
  flutter_image_compress: ^2.3.0
  image: ^3.0.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator:
  floor_generator:
  build_runner:
  freezed:
  test:

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    # - assets/icons/
    # - assets/svgs/
    - assets/images/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 400
